services:
  api:
    build:
      context: .
      dockerfile: NotesApp.Api/Docker/Dockerfile
    container_name: notesapp-api-container
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql-container;Database=NotesAppDb;User=root;Password=password;
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "5000:8080"

  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: NotesAppDb
    volumes:
      - notesapp_mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  notes-migration:
    build:
      context: .
      dockerfile: NotesApp.Api/Docker/Dockerfile.migrations
    container_name: notes-migration
    tty: true
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

volumes:
  notesapp_mysql_data:

networks:
  app-network:
